### ISSUE TITLE
すべての validation を通さないと update できない。

### ISSUE THREAD

**Issue by kminiatures** [answer/ans-key_value_store#4]
１つずつ設定可能であってほしい

```
[8] pry(main)> Setting.data.update! domain: 'bambi-fukuen-koba.ans-web.co.jp'
ActiveRecord::RecordInvalid: バリデーションに失敗しました。 Mail user deviseを入力してください。
from /var/www/bambi/devel/koba/fukuen/vendor/bundle/ruby/2.2.0/gems/ans-key_value_store-0.0.3/lib/ans/key_value_store/data.rb:58:in `update!'
[9] pry(main)> Setting.data.update domain: 'bambi-fukuen-koba.ans-web.co.jp'
=> false
[10] pry(main)> Setting.data.update! domain: 'bambi-fukuen-koba.ans-web.co.jp'
ActiveRecord::RecordInvalid: バリデーションに失敗しました。 Mail user deviseを入力してください。
from /var/www/bambi/devel/koba/fukuen/vendor/bundle/ruby/2.2.0/gems/ans-key_value_store-0.0.3/lib/ans/key_value_store/data.rb:58:in `update!'
[11] pry(main)> Setting.data.update! domain: 'bambi-fukuen-koba.ans-web.co.jp', mail_user_device: 'info'
ActiveRecord::RecordInvalid: バリデーションに失敗しました。 Mail user deviseを入力してください。
from /var/www/bambi/devel/koba/fukuen/vendor/bundle/ruby/2.2.0/gems/ans-key_value_store-0.0.3/lib/ans/key_value_store/data.rb:58:in `update!'
[12] pry(main)> Setting.data.update! domain: 'bambi-fukuen-koba.ans-web.co.jp', mail_user_devise: 'info'
   (0.3ms)  BEGIN
  Setting Load (0.5ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`key` = 'domain' LIMIT 1
  SQL (0.3ms)  INSERT INTO `settings` (`key`, `value`, `created_at`, `updated_at`) VALUES ('domain', 'bambi-fukuen-koba.ans-web.co.jp', '2015-02-13 19:12:52.706709', '2015-02-13 19:12:52.706709')
  Setting Load (0.3ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`key` = 'mail_user_devise' LIMIT 1
  SQL (0.2ms)  INSERT INTO `settings` (`key`, `value`, `created_at`, `updated_at`) VALUES ('mail_user_devise', 'info', '2015-02-13 19:12:52.710980', '2015-02-13 19:12:52.710980')
   (41.0ms)  COMMIT
=> nil
```

**Comment by ghost** [comment]
修正しました
